[package]
name = "sokoban-bindgen-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
sokoban-bindgen = { path = "../sokoban-bindgen" }

[build-dependencies]
cbindgen = "0.26.0"
